Award:
  login:        # ---> [20, 10, 0]
    - 20        # 硬币奖励
    - 10        # 好感度奖励
    - 0         # 经验值奖励
  sign:         # ---> [[30, 60], 5, 100]
    - [30, 60]  
    - 5
    - 100

Level:
  # 初始经验阈值
  base_exp: 150
  # 经验系数
  cardinality: 1.2
  # 最大等级
  max_level: 60
