ConfigVersion: "1.0.0"

Award:
  # 金币奖励
  Coin:
    login: 50      
    sign: [20, 60]
  # 好感度奖励
  Jrrp:
    login: 20
    sign: 10
  # 经验值奖励
  Exp:
    login: 0
    sign: 10


WithGoCQHTTP:
  enabled: {is_use_with_gocqhttp}
  accounts: {accounts}

  download_domain: "{download_domain}"
  download_version: "v1.1.0"

  gocqhttp_webui_username: "Sora"
  gocqhttp_webui_password: "Sora231010"
